services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - EXECUTIONS_PROCESS=main
    volumes:
      - n8n_data:/home/node/.n8n
      - ./storage/n8n:/files
    healthcheck:
      test: ["CMD", "node", "/usr/local/bin/checkHealth.js"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  n8n_data:
